void setText() {
    font.loadFromFile("../font/OceanSummer.ttf");
    text_cd_0.setFillColor(Color::White);
    text_cd_1.setFillColor(Color::White);
    text_cd_2.setFillColor(Color::White);
    text_cd_3.setFillColor(Color::White);
    text_cd_4.setFillColor(Color::White);
    text_cd_5.setFillColor(Color::White);
    text_cd_6.setFillColor(Color::White);
    text_cd_7.setFillColor(Color::White);
    text_cd_8.setFillColor(Color::White);
    text.setFillColor(Color::White);
    player_stats_hp.setFillColor(Color::White);
    player_stats_hp.setStyle(sf::Text::Bold);
    player_stats_mp.setFillColor(Color::White);
    player_stats_mp.setStyle(sf::Text::Bold);
    player_stats_lvl.setFillColor(Color::White);
    player_stats_lvl.setStyle(sf::Text::Bold);
}
